### ISSUE TITLE
code in main.py

### ISSUE THREAD

**Issue by wushunshun** [zhilin007/FFA-Net#1]
code in main.py 19th line
why mean=[0.45627367, 0.38360259, 0.36426624]#clear?
how to calculate mean?
thank you!

**Comment by zhilin007** [comment]
This is a redundant line in our project,it will be deleted later. 'mean' meaning to calculate the mean of RGB channels. You can use 'mean=np.mean(imgs,axis=(0,1,2))' to do that.
