### ISSUE TITLE
result on real hazy image look not good

### ISSUE THREAD

**Issue by PhanVinhLong** [zhilin007/FFA-Net#2]
I have use you trained models to test on real hazy image (from google) but it look not good. Have I done something wrong?
(left: hazy imge - right: prediction using ots model)
![image](https://user-images.githubusercontent.com/38372544/70452405-a794e580-1ad9-11ea-9fa7-e93e28cf9170.png)
![image](https://user-images.githubusercontent.com/38372544/70452081-1aea2780-1ad9-11ea-8925-48f796e06b62.png)
![image](https://user-images.githubusercontent.com/38372544/70452125-2d646100-1ad9-11ea-8f65-fb12e05b7e07.png)

**Comment by ninesun127** [comment]
This is normal. Our network results are not so perfect in real hazy images, but it still applies to other networks. It's also very simple to understand that the training images and real hazy images come from two totally different domains. We can't expect excellent performance on both different domains, which involves the domain adaptation field.

**Comment by PhanVinhLong** [comment]
> 
> 
> This is normal. Our network results are not so perfect in real hazy images, but it still applies to other networks. It's also very simple to understand that the training images and real hazy images come from two totally different domains. We can't expect excellent performance on both different domains, which involves the domain adaptation field.

Have your paper been accepted at any conf? How can I cite it? Thanks a lot.

**Comment by ninesun127** [comment]
our paper was accepted by AAAI2020，but it has not been published officially.
you can cite arxiv version or wait the official AAAI2020 version.
At last.thanks for your interest



------------------ Original ------------------

**Comment by PhanVinhLong** [comment]
> 
> our paper was accepted by AAAI2020，but it has not been published officially. you can cite arxiv version or wait the official AAAI2020 version. At last.thanks for your interest
> […](#)
> ------------------ Original ------------------ From: Phan Vĩnh Long <notifications@github.com&gt; Date: Wed,Dec 11,2019 0:18 AM To: zhilin007/FFA-Net <FFA-Net@noreply.github.com&gt; Cc: ninesun127 <714189111@qq.com&gt;, Comment <comment@noreply.github.com&gt; Subject: Re: [zhilin007/FFA-Net] result on real hazy image look not good (#2) This is normal. Our network results are not so perfect in real hazy images, but it still applies to other networks. It's also very simple to understand that the training images and real hazy images come from two totally different domains. We can't expect excellent performance on both different domains, which involves the domain adaptation field. Have your paper been accepted at any conf? How can I cite it? Thanks a lot. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks for your response.
