### ISSUE TITLE
Fake Experiment and Fake Paper

### ISSUE THREAD

**Issue by LT1st** [zhilin007/FFA-Net#23]
We have asked AAAI to recall your paper, as it's impossible to achieve the same perfmance in your paper.
Vrevision it if there is something wrong. Or we will let your college and mentor informed.
Academic fraud is shameful.

**Comment by PaulTHong** [comment]
Hello, sorry to bother you. I wonder what's the problem? I can't re-implement the reported results on OTS.

**Comment by Agrowingsix** [comment]
yes，I agree with you

**Comment by Cynicarlos** [comment]
1300 + citations, that is crazy!!!
